### ISSUE TITLE
ImportError: cannot import name 'Proc' from 'easyprocess'

### ISSUE THREAD

**Issue by cactorium** [ponty/pyavrutils#2]
Hello! I get this error message when trying to use `pysimavr`, which seems to come from this package:

```
>>> import pysimavr.avr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kelvin/.local/lib/python3.8/site-packages/pysimavr/avr.py", line 2, in <module>
    from pyavrutils.avrsize import AvrSize
  File "/home/kelvin/.local/lib/python3.8/site-packages/pyavrutils/__init__.py", line 10, in <module>
    from .avrgcc import *
  File "/home/kelvin/.local/lib/python3.8/site-packages/pyavrutils/avrgcc.py", line 1, in <module>
    from easyprocess import Proc, extract_version
ImportError: cannot import name 'Proc' from 'easyprocess' (/home/kelvin/.local/lib/python3.8/site-packages/easyprocess/__init__.py)
```

Would you have any advice on how to troubleshoot? Thanks for you time!

**Comment by adamples** [comment]
Had the same problem. The workaround is to install older version of the package:

    python -m pip install easyprocess==0.2.10
